/*
 * Automatically generated C config: don't edit
 */
#define AUTOCONF_INCLUDED
#define CONFIG_IN_UBOOT 1

/*
 * SDK Options
 */

/*
 * Chip Support
 */

/*
 * Select your target MAC chip(s)
 */
#undef  CONFIG_SDK_RTL8380
#undef  CONFIG_SDK_RTL8390
#define CONFIG_SDK_RTL9300 1
#undef  CONFIG_SDK_RTL9310

/*
 * Select your target PHYs chip
 */
#undef  CONFIG_SDK_RTL8208D
#undef  CONFIG_SDK_RTL8208G
#undef  CONFIG_SDK_RTL8208L
#undef  CONFIG_SDK_RTL8212B
#undef  CONFIG_SDK_RTL8214B
#undef  CONFIG_SDK_RTL8214FB
#undef  CONFIG_SDK_RTL8214FC
#undef  CONFIG_SDK_RTL8214C
#undef  CONFIG_SDK_RTL8214QF
#define CONFIG_SDK_RTL8218B 1
#define CONFIG_SDK_RTL8218D 1
#undef  CONFIG_SDK_RTL8218E
#undef  CONFIG_SDK_RTL8218FB
#undef  CONFIG_SDK_RTL8224QF
#undef  CONFIG_SDK_RTL8226
#undef  CONFIG_SDK_RTL8295R
#undef  CONFIG_SDK_RTL826X
#undef  CONFIG_SDK_RTL826XI
#undef  CONFIG_SDK_RTL825X
#undef  CONFIG_SDK_RTL825XI
#undef  CONFIG_SDK_RTL825XL
#undef  CONFIG_SDK_RTL8224
#undef  CONFIG_SDK_RTL826XB

/*
 * Select your target Peripheral chip
 */
#define CONFIG_SDK_RTL8231 1

/*
 * Select customer defined PHYs chip
 */
#undef  CONFIG_SDK_PHY_CUST1
#undef  CONFIG_SDK_PHY_CUST2
#undef  CONFIG_SDK_PHY_CUST3
#undef  CONFIG_SDK_PHY_CUST4
#undef  CONFIG_SDK_PHY_CUST5
#undef  CONFIG_SDK_PHY_GPY2xx
#define CONFIG_SDK_EXPERIMENTAL_RTL8211FS 1

/*
 * CPU
 */
#undef  CONFIG_SDK_EXTERNAL_CPU
#undef  CONFIG_SDK_ENDIAN_LITTLE
#define CONFIG_UBOOT_SDK_SUPPORT 1

/*
 * SDK Driver
 */

/*
 * Rtcore Driver support
 */
#define CONFIG_SDK_DRIVER_RTCORE 1
#define CONFIG_SDK_DRIVER_RTCORE_IN_LINUX_KERNEL 1
#define CONFIG_SDK_DRIVER_NIC 1
#undef  CONFIG_SDK_DRIVER_EXTC_NIC
#undef  CONFIG_SDK_DRIVER_EXTC_PCI
#define CONFIG_SDK_DRIVER_GPIO 1
#define CONFIG_SDK_DRIVER_SPI 1
#define CONFIG_SDK_DRIVER_I2C 1
#undef  CONFIG_SDK_TC_DRV
#undef  CONFIG_SDK_DRIVER_WATCHDOG
#define CONFIG_SDK_UART1 1
#undef  CONFIG_SDK_DRIVER_NIC_R9310
#define CONFIG_SDK_DRIVER_NIC_R9300 1
#undef  CONFIG_SDK_DRIVER_NIC_R8390
#undef  CONFIG_SDK_DRIVER_NIC_R8380
#undef  CONFIG_SDK_DRIVER_I2C_R9310
#define CONFIG_SDK_DRIVER_I2C_R9300 1
#undef  CONFIG_SDK_DRIVER_I2C_R8390
#undef  CONFIG_SDK_DRIVER_I2C_R8380

/*
 * BSP Option
 */
#define CONFIG_SDK_BSP_FLASH 1
#define CONFIG_FLASH_LAYOUT_TYPE5 1
#define CONFIG_TURNKEY_SYSINFO 1
#define CONFIG_DUAL_IMAGE 1
#undef  CONFIG_SENAO_FLASH_LAYOUT_TYPE5_JFFS2_CFG_RECOVERY
#undef  CONFIG_EPS_FLASH_LAYOUT_RESCUE_NONE
#define CONFIG_SDK_SPI_DEV_NONE 1
#undef  CONFIG_SDK_SPI_DEV_1
#undef  CONFIG_SDK_SPI_DEV_2
#undef  CONFIG_SDK_SPI_DEV_3
#undef  CONFIG_SDK_SPI_DEV_4
#undef  CONFIG_SDK_SPI_DEV_5
#define CONFIG_SDK_BSP_SPI_NOR_BOOT 1
#undef  CONFIG_SDK_BSP_SPI_NAND_BOOT

/*
 * Misc Option
 */
#undef  CONFIG_SDK_EXPERIMENTAL
#undef  CONFIG_SDK_FPGA_PLATFORM
#define CONFIG_SDK_HW_PROFILE_PROBE_GPIO 1
#undef  CONFIG_SDK_HW_PROFILE_PROBE_UBOOT_ENV
#define CONFIG_SDK_OS_VERSION "Linux 3.18.24"
#define CONFIG_SDK_COMPILER_VERSION "GCC 4.8.5"
#define CONFIG_SDK_LIBC_VERSION "uClibc-0.9.33.2 with NPTL"
#define CONFIG_MISC_INIT_R 1

/*
 * Board
 */
#define CONFIG_UART0 1
#undef  CONFIG_UART1
#undef  CONFIG_INTERRUPT_SUPPORT
#define CONFIG_BOOT_SPI_NOR 1
#undef  CONFIG_BOOT_SPI_NAND

/*
 * Supported Commands
 */
#define CONFIG_CMDLINE_EDITING 1
#define CONFIG_CMD_FLASH 1
#define CONFIG_CMD_MEMORY 1
#define CONFIG_CMD_IMI 1
#undef  CONFIG_CMD_ENV
#undef  CONFIG_CMD_DUMPREGS
#define CONFIG_CMD_LOADB 1
#define CONFIG_CMD_LOADS 1
#define CONFIG_CMD_SAVEENV 1

/*
 * Menu Boot Options
 */
#define CONFIG_RTK_BOOT 1
#define CONFIG_TFTP_DOWNLOAD 1
#undef  CONFIG_SERIAL_DOWNLOAD
#undef  CONFIG_ICE_DOWNLOAD
#undef  CONFIG_STANDALONE_APP
#define CONFIG_CMD_NET 1
#define CONFIG_NET_MULTI 1
#define CONFIG_AUTOBOOT_PROMPT ""
#define CONFIG_CMD_RTK 1
#define CONFIG_CMD_RUN 1

/*
 * Networking
 */
#define CONFIG_ETHADDR 00:02:6F:00:00:00
#define CONFIG_CMD_NET 1
#define CONFIG_CMD_PING 1
#define CONFIG_NET_MULTI 1
#undef  CONFIG_CMD_WEB
#define CONFIG_IPADDR 192.168.1.1
#define CONFIG_SERVERIP 192.168.1.111

/*
 * Miscellaneous
 */
#define CFG_PROMPT "RTL9300 # "
#define CONFIG_SYS_TEXT_BASE 0x83F00000
#define CONFIG_BOOTDELAY 1
#define CONFIG_BOOTCOMMAND "boota"
#define CONFIG_BOARDVERSION ""
#define CONFIG_BOARDMODEL "RTL8393M_DEMO"
#define CONFIG_BOOTARGS ""
#define CONFIG_POSTWORD ""
#define CONFIG_BAUDRATE 115200
#define CONFIG_LZMA 1
#undef  CONFIG_HWP_RTL8218_AUTOSELECT
#define CONFIG_ENABLE_SPI_NAND_DRIVER 1
#undef  CONFIG_RTK_USB_EHCI_HCD

/*
 * System
 */

/*
 * System Configuration
 */
#undef  CONFIG_RTOS_TOOLCHAIN_USED
#undef  CONFIG_ENABLE_IH_MAGIC_NUMBER_CHK
#define CONFIG_IH_MAGIC_NUMBER 0x93000000
#define CONFIG_SENAO_BOOT_VERSION "03.00.01"
#define CONFIG_SENAO_BOOT_VERSION_UPDATE 1
#define CONFIG_SENAO_BOARD_SUPPORT 1
#define CONFIG_SENAO_RESET_FLAG "0"
#define CONFIG_SENAO_IMMORTAL_FLAG "0"
#define CONFIG_SENAO_SGS_MODEL ""
#define CONFIG_SENAO_MENUKEY 1
#define CONFIG_SENAO_DEFAULT_MAGIC_NUMBER 1
#define CONFIG_SENAO_GPIO_INIT 1
#define CONFIG_SENAO_DEFAULT_SN "000000001"
#undef  CONFIG_ENV_CRC_ERROR_SAVE_DEFAULT_ENV
#undef  CONFIG_SENAO_RESCUE_IMAGE
#define CONFIG_SENAO_RESCUE_IMAGE_FLAG "rescue_none"
#undef  CONFIG_SENAO_RESCUE_LITEOS
#undef  CONFIG_SENAO_RESET_CHG_PARTITION
#undef  CONFIG_SENAO_CUSTOMER_UBOOT
#undef  CONFIG_CMD_DHCP
#undef  CONFIG_CMD_IMMORTAL
#define CONFIG_SPI_NAND 1
#define CONFIG_SPI_NAND_FLASH_INIT_FIRST 1
#define CONFIG_SPI_NAND_FLASH 1
#define CONFIG_ECC_ENGINE_INIT 1
#define CONFIG_ECC_ENGINE 1
#define CONFIG_CMD_SPI_NAND 1
#define CONFIG_CMD_SF 1
#define CONFIG_NOR_SPIF_G3 1
#define CONFIG_SPI_NOR_FLASH 1
#define CONFIG_SPI_NAND_FLASH_G3 1
#define CONFIG_ECC_ENGINE_G2 1
#define CONFIG_OTTO40_PRJNAME "9300_nor_demo"
#define CONFIG_ENV_OVERWRITE 1
#define CONFIG_CMD_UBI 1
#define CONFIG_RBTREE 1
#define CONFIG_CMD_SPI_NAND 1
#define CONFIG_SPI_NAND_FLASH 1
#define CONFIG_ECC_ENGINE 1
#define CONFIG_LZMA 1
#define CONFIG_CMD_MTDPARTS 1
#define CONFIG_MTD_DEVICE 1
#define CONFIG_MTD_PARTITIONS 1
#define CONFIG_SYS_MAX_NAND_DEVICE 0x1
