/*
 * Copyright (C) 2009-2020 Realtek Semiconductor Corp.
 * All Rights Reserved.
 *
 * This program is the proprietary software of Realtek Semiconductor
 * Corporation and/or its licensors, and only be used, duplicated,
 * modified or distributed under the authorized license from Realtek.
 *
 * ANY USE OF THE SOFTWARE OTHER THAN AS AUTHORIZED UNDER
 * THIS LICENSE OR COPYRIGHT LAW IS PROHIBITED.
 *
 * $Revision$
 * $Date$
 *
 * Purpose : Define UBoot utility Glude layer
 *
 * Feature :
 *
 */

#ifndef __UBOOT_UTIL_H__
#define __UBOOT_UTIL_H__
#include <generated/version_autogenerated.h>

#define UBOOT_VER_OFT           8
#define UBOOT_VER_CALC(a,b)     (((a) << UBOOT_VER_OFT) + (b))
#define UBOOT_VER_CODE          UBOOT_VER_CALC(U_BOOT_VERSION_NUM, U_BOOT_VERSION_NUM_PATCH)


#if (UBOOT_VER_CODE < UBOOT_VER_CALC(2019, 10))
#define GETENV(name)            getenv(name)
#define SETENV                  setenv
#define SAVEENV()               saveenv()
#define ENV_SET_DEFAULT(s,f)    set_default_env(s)
#else
#define GETENV(name)            env_get(name)
#define SETENV(name,val)        env_set(name,val)
#define SAVEENV()               env_save()
#define ENV_SET_DEFAULT(s,f)    env_set_default(s,f)
#endif

#if (UBOOT_VER_CODE < UBOOT_VER_CALC(2017, 7))
#define PACKET_SEND(pkt,len)    NetSendPacket(pkt,len)
#else
#define PACKET_SEND(pkt,len)    net_send_packet(pkt,len)
#endif

#if (UBOOT_VER_CODE < UBOOT_VER_CALC(2021, 1))
#define GETCHAR                 getc
#else
#define GETCHAR                 getchar
#endif

#if (UBOOT_VER_CODE < UBOOT_VER_CALC(2020, 4))
    #define CMD_TBL_T       cmd_tbl_t
#else
    typedef struct cmd_tbl CMD_TBL_T;
#endif

#endif /* __UBOOT_UTIL_H__ */
