/*
 * Copyright (C) 2020 Realtek Semiconductor Corp.
 * All Rights Reserved.
 *
 * This program is the proprietary software of Realtek Semiconductor
 * Corporation and/or its licensors, and only be used, duplicated,
 * modified or distributed under the authorized license from Realtek.
 *
 * ANY USE OF THE SOFTWARE OTHER THAN AS AUTHORIZED UNDER
 * THIS LICENSE OR COPYRIGHT LAW IS PROHIBITED.
 *
 * $Revision$
 * $Date$
 *
 * Purpose : Definition the basic types in the SDK.
 *
 * Feature : type definition
 *
 */

/*
 * Please DO NOT edit this file, it is auto generated.
 */

#ifndef __RTK_FEATURE_DEF_H__
#define __RTK_FEATURE_DEF_H__


#if (!defined(CONFIG_SDK_FEATURED_MINISDK))
    #define F_000000(mapper_cb, func)      mapper_cb = func
#else
    #define F_000000(mapper_cb, func)      do { } while(0)
#endif /* (!defined(CONFIG_SDK_FEATURED_MINISDK)) */

#if (defined(__BOOTLOADER__)) || (!defined(CONFIG_SDK_FEATURED_MINISDK))
    #define F_00000U(mapper_cb, func)      mapper_cb = func
#else
    #define F_00000U(mapper_cb, func)      do { } while(0)
#endif /* (defined(__BOOTLOADER__)) || (!defined(CONFIG_SDK_FEATURED_MINISDK)) */

#if (defined(CONFIG_SDK_MINISDK_NET)) || (!defined(CONFIG_SDK_FEATURED_MINISDK))
    #define F_0000N0(mapper_cb, func)      mapper_cb = func
#else
    #define F_0000N0(mapper_cb, func)      do { } while(0)
#endif /* (defined(CONFIG_SDK_MINISDK_NET)) || (!defined(CONFIG_SDK_FEATURED_MINISDK)) */

#if (defined(CONFIG_SDK_MINISDK_NET) || defined(__BOOTLOADER__)) || (!defined(CONFIG_SDK_FEATURED_MINISDK))
    #define F_0000NU(mapper_cb, func)      mapper_cb = func
#else
    #define F_0000NU(mapper_cb, func)      do { } while(0)
#endif /* (defined(CONFIG_SDK_MINISDK_NET) || defined(__BOOTLOADER__)) || (!defined(CONFIG_SDK_FEATURED_MINISDK)) */

#if (defined(CONFIG_SDK_MINISDK_PHY)) || (!defined(CONFIG_SDK_FEATURED_MINISDK))
    #define F_000Y00(mapper_cb, func)      mapper_cb = func
#else
    #define F_000Y00(mapper_cb, func)      do { } while(0)
#endif /* (defined(CONFIG_SDK_MINISDK_PHY)) || (!defined(CONFIG_SDK_FEATURED_MINISDK)) */

#if (defined(CONFIG_SDK_MINISDK_PHY) || defined(__BOOTLOADER__)) || (!defined(CONFIG_SDK_FEATURED_MINISDK))
    #define F_000Y0U(mapper_cb, func)      mapper_cb = func
#else
    #define F_000Y0U(mapper_cb, func)      do { } while(0)
#endif /* (defined(CONFIG_SDK_MINISDK_PHY) || defined(__BOOTLOADER__)) || (!defined(CONFIG_SDK_FEATURED_MINISDK)) */

#if (defined(CONFIG_SDK_MINISDK_PHY) || defined(CONFIG_SDK_MINISDK_NET)) || (!defined(CONFIG_SDK_FEATURED_MINISDK))
    #define F_000YN0(mapper_cb, func)      mapper_cb = func
#else
    #define F_000YN0(mapper_cb, func)      do { } while(0)
#endif /* (defined(CONFIG_SDK_MINISDK_PHY) || defined(CONFIG_SDK_MINISDK_NET)) || (!defined(CONFIG_SDK_FEATURED_MINISDK)) */

#if (defined(CONFIG_SDK_MINISDK_PHY) || defined(CONFIG_SDK_MINISDK_NET) || defined(__BOOTLOADER__)) || (!defined(CONFIG_SDK_FEATURED_MINISDK))
    #define F_000YNU(mapper_cb, func)      mapper_cb = func
#else
    #define F_000YNU(mapper_cb, func)      do { } while(0)
#endif /* (defined(CONFIG_SDK_MINISDK_PHY) || defined(CONFIG_SDK_MINISDK_NET) || defined(__BOOTLOADER__)) || (!defined(CONFIG_SDK_FEATURED_MINISDK)) */

#if (defined(CONFIG_SDK_MINISDK_D)) || (!defined(CONFIG_SDK_FEATURED_MINISDK))
    #define F_00D000(mapper_cb, func)      mapper_cb = func
#else
    #define F_00D000(mapper_cb, func)      do { } while(0)
#endif /* (defined(CONFIG_SDK_MINISDK_D)) || (!defined(CONFIG_SDK_FEATURED_MINISDK)) */

#if (defined(CONFIG_SDK_MINISDK_D) || defined(__BOOTLOADER__)) || (!defined(CONFIG_SDK_FEATURED_MINISDK))
    #define F_00D00U(mapper_cb, func)      mapper_cb = func
#else
    #define F_00D00U(mapper_cb, func)      do { } while(0)
#endif /* (defined(CONFIG_SDK_MINISDK_D) || defined(__BOOTLOADER__)) || (!defined(CONFIG_SDK_FEATURED_MINISDK)) */

#if (defined(CONFIG_SDK_MINISDK_D) || defined(CONFIG_SDK_MINISDK_NET)) || (!defined(CONFIG_SDK_FEATURED_MINISDK))
    #define F_00D0N0(mapper_cb, func)      mapper_cb = func
#else
    #define F_00D0N0(mapper_cb, func)      do { } while(0)
#endif /* (defined(CONFIG_SDK_MINISDK_D) || defined(CONFIG_SDK_MINISDK_NET)) || (!defined(CONFIG_SDK_FEATURED_MINISDK)) */

#if (defined(CONFIG_SDK_MINISDK_D) || defined(CONFIG_SDK_MINISDK_NET) || defined(__BOOTLOADER__)) || (!defined(CONFIG_SDK_FEATURED_MINISDK))
    #define F_00D0NU(mapper_cb, func)      mapper_cb = func
#else
    #define F_00D0NU(mapper_cb, func)      do { } while(0)
#endif /* (defined(CONFIG_SDK_MINISDK_D) || defined(CONFIG_SDK_MINISDK_NET) || defined(__BOOTLOADER__)) || (!defined(CONFIG_SDK_FEATURED_MINISDK)) */

#if (defined(CONFIG_SDK_MINISDK_D) || defined(CONFIG_SDK_MINISDK_PHY)) || (!defined(CONFIG_SDK_FEATURED_MINISDK))
    #define F_00DY00(mapper_cb, func)      mapper_cb = func
#else
    #define F_00DY00(mapper_cb, func)      do { } while(0)
#endif /* (defined(CONFIG_SDK_MINISDK_D) || defined(CONFIG_SDK_MINISDK_PHY)) || (!defined(CONFIG_SDK_FEATURED_MINISDK)) */

#if (defined(CONFIG_SDK_MINISDK_D) || defined(CONFIG_SDK_MINISDK_PHY) || defined(__BOOTLOADER__)) || (!defined(CONFIG_SDK_FEATURED_MINISDK))
    #define F_00DY0U(mapper_cb, func)      mapper_cb = func
#else
    #define F_00DY0U(mapper_cb, func)      do { } while(0)
#endif /* (defined(CONFIG_SDK_MINISDK_D) || defined(CONFIG_SDK_MINISDK_PHY) || defined(__BOOTLOADER__)) || (!defined(CONFIG_SDK_FEATURED_MINISDK)) */

#if (defined(CONFIG_SDK_MINISDK_D) || defined(CONFIG_SDK_MINISDK_PHY) || defined(CONFIG_SDK_MINISDK_NET)) || (!defined(CONFIG_SDK_FEATURED_MINISDK))
    #define F_00DYN0(mapper_cb, func)      mapper_cb = func
#else
    #define F_00DYN0(mapper_cb, func)      do { } while(0)
#endif /* (defined(CONFIG_SDK_MINISDK_D) || defined(CONFIG_SDK_MINISDK_PHY) || defined(CONFIG_SDK_MINISDK_NET)) || (!defined(CONFIG_SDK_FEATURED_MINISDK)) */

#if (defined(CONFIG_SDK_MINISDK_D) || defined(CONFIG_SDK_MINISDK_PHY) || defined(CONFIG_SDK_MINISDK_NET) || defined(__BOOTLOADER__)) || (!defined(CONFIG_SDK_FEATURED_MINISDK))
    #define F_00DYNU(mapper_cb, func)      mapper_cb = func
#else
    #define F_00DYNU(mapper_cb, func)      do { } while(0)
#endif /* (defined(CONFIG_SDK_MINISDK_D) || defined(CONFIG_SDK_MINISDK_PHY) || defined(CONFIG_SDK_MINISDK_NET) || defined(__BOOTLOADER__)) || (!defined(CONFIG_SDK_FEATURED_MINISDK)) */


#if (defined(CONFIG_SDK_MINISDK_PHY)) || (!defined(CONFIG_SDK_FEATURED_MINISDK))
    #define F_000Y00(mapper_cb, func)      mapper_cb = func
#else
    #define F_000Y00(mapper_cb, func)      do { } while(0)
#endif /* (defined(CONFIG_SDK_MINISDK_PHY)) || (!defined(CONFIG_SDK_FEATURED_MINISDK)) */

#if (defined(CONFIG_SDK_MINISDK_PHY) || defined(__BOOTLOADER__)) || (!defined(CONFIG_SDK_FEATURED_MINISDK))
    #define F_000Y0U(mapper_cb, func)      mapper_cb = func
#else
    #define F_000Y0U(mapper_cb, func)      do { } while(0)
#endif /* (defined(CONFIG_SDK_MINISDK_PHY) || defined(__BOOTLOADER__)) || (!defined(CONFIG_SDK_FEATURED_MINISDK)) */

#if (defined(CONFIG_SDK_MINISDK_PHY) || defined(CONFIG_SDK_MINISDK_NET)) || (!defined(CONFIG_SDK_FEATURED_MINISDK))
    #define F_000YN0(mapper_cb, func)      mapper_cb = func
#else
    #define F_000YN0(mapper_cb, func)      do { } while(0)
#endif /* (defined(CONFIG_SDK_MINISDK_PHY) || defined(CONFIG_SDK_MINISDK_NET)) || (!defined(CONFIG_SDK_FEATURED_MINISDK)) */

#if (defined(CONFIG_SDK_MINISDK_PHY) || defined(CONFIG_SDK_MINISDK_NET) || defined(__BOOTLOADER__)) || (!defined(CONFIG_SDK_FEATURED_MINISDK))
    #define F_000YNU(mapper_cb, func)      mapper_cb = func
#else
    #define F_000YNU(mapper_cb, func)      do { } while(0)
#endif /* (defined(CONFIG_SDK_MINISDK_PHY) || defined(CONFIG_SDK_MINISDK_NET) || defined(__BOOTLOADER__)) || (!defined(CONFIG_SDK_FEATURED_MINISDK)) */

#if (defined(CONFIG_SDK_MINISDK_D)) || (!defined(CONFIG_SDK_FEATURED_MINISDK))
    #define F_00D000(mapper_cb, func)      mapper_cb = func
#else
    #define F_00D000(mapper_cb, func)      do { } while(0)
#endif /* (defined(CONFIG_SDK_MINISDK_D)) || (!defined(CONFIG_SDK_FEATURED_MINISDK)) */

#if (defined(CONFIG_SDK_MINISDK_D) || defined(__BOOTLOADER__)) || (!defined(CONFIG_SDK_FEATURED_MINISDK))
    #define F_00D00U(mapper_cb, func)      mapper_cb = func
#else
    #define F_00D00U(mapper_cb, func)      do { } while(0)
#endif /* (defined(CONFIG_SDK_MINISDK_D) || defined(__BOOTLOADER__)) || (!defined(CONFIG_SDK_FEATURED_MINISDK)) */

#if (defined(CONFIG_SDK_MINISDK_D) || defined(CONFIG_SDK_MINISDK_NET)) || (!defined(CONFIG_SDK_FEATURED_MINISDK))
    #define F_00D0N0(mapper_cb, func)      mapper_cb = func
#else
    #define F_00D0N0(mapper_cb, func)      do { } while(0)
#endif /* (defined(CONFIG_SDK_MINISDK_D) || defined(CONFIG_SDK_MINISDK_NET)) || (!defined(CONFIG_SDK_FEATURED_MINISDK)) */

#if (defined(CONFIG_SDK_MINISDK_D) || defined(CONFIG_SDK_MINISDK_NET) || defined(__BOOTLOADER__)) || (!defined(CONFIG_SDK_FEATURED_MINISDK))
    #define F_00D0NU(mapper_cb, func)      mapper_cb = func
#else
    #define F_00D0NU(mapper_cb, func)      do { } while(0)
#endif /* (defined(CONFIG_SDK_MINISDK_D) || defined(CONFIG_SDK_MINISDK_NET) || defined(__BOOTLOADER__)) || (!defined(CONFIG_SDK_FEATURED_MINISDK)) */

#if (defined(CONFIG_SDK_MINISDK_D) || defined(CONFIG_SDK_MINISDK_PHY)) || (!defined(CONFIG_SDK_FEATURED_MINISDK))
    #define F_00DY00(mapper_cb, func)      mapper_cb = func
#else
    #define F_00DY00(mapper_cb, func)      do { } while(0)
#endif /* (defined(CONFIG_SDK_MINISDK_D) || defined(CONFIG_SDK_MINISDK_PHY)) || (!defined(CONFIG_SDK_FEATURED_MINISDK)) */

#if (defined(CONFIG_SDK_MINISDK_D) || defined(CONFIG_SDK_MINISDK_PHY) || defined(__BOOTLOADER__)) || (!defined(CONFIG_SDK_FEATURED_MINISDK))
    #define F_00DY0U(mapper_cb, func)      mapper_cb = func
#else
    #define F_00DY0U(mapper_cb, func)      do { } while(0)
#endif /* (defined(CONFIG_SDK_MINISDK_D) || defined(CONFIG_SDK_MINISDK_PHY) || defined(__BOOTLOADER__)) || (!defined(CONFIG_SDK_FEATURED_MINISDK)) */

#if (defined(CONFIG_SDK_MINISDK_D) || defined(CONFIG_SDK_MINISDK_PHY) || defined(CONFIG_SDK_MINISDK_NET)) || (!defined(CONFIG_SDK_FEATURED_MINISDK))
    #define F_00DYN0(mapper_cb, func)      mapper_cb = func
#else
    #define F_00DYN0(mapper_cb, func)      do { } while(0)
#endif /* (defined(CONFIG_SDK_MINISDK_D) || defined(CONFIG_SDK_MINISDK_PHY) || defined(CONFIG_SDK_MINISDK_NET)) || (!defined(CONFIG_SDK_FEATURED_MINISDK)) */

#if (defined(CONFIG_SDK_MINISDK_D) || defined(CONFIG_SDK_MINISDK_PHY) || defined(CONFIG_SDK_MINISDK_NET) || defined(__BOOTLOADER__)) || (!defined(CONFIG_SDK_FEATURED_MINISDK))
    #define F_00DYNU(mapper_cb, func)      mapper_cb = func
#else
    #define F_00DYNU(mapper_cb, func)      do { } while(0)
#endif /* (defined(CONFIG_SDK_MINISDK_D) || defined(CONFIG_SDK_MINISDK_PHY) || defined(CONFIG_SDK_MINISDK_NET) || defined(__BOOTLOADER__)) || (!defined(CONFIG_SDK_FEATURED_MINISDK)) */


#endif /* __RTK_FEATURE_DEF_H__ */




