/*
 *
 * Automatically generated file; DO NOT EDIT.
 * SDK Configuration
 *
 */
#define CONFIG_SDK_DRIVER_NIC_USER_MODE 1
#define CONFIG_SDK_BSP_MTD_ECC_G2 1
#define CONFIG_SDK_BSP_MTD_SPI 1
#define CONFIG_SDK_RTL826X 1
#define CONFIG_SDK_RTL8224 1
#define CONFIG_SDK_LIBC_VERSION "uClibc-0.9.33.2 with NPTL"
#define CONFIG_SDK_DUMP_REG_WITH_NAME 1
#define CONFIG_SDK_DEBUG_LOG_TYPE_LEVEL 1
#define CONFIG_SDK_HW_PROFILE_PROBE_UBOOT_ENV 1
#define CONFIG_BDINFO_MTD_INDEX 0x1
#define CONFIG_SDK_RTL8218E 1
#define CONFIG_TURNKEY_SYSINFO 1
#define CONFIG_SDK_OS_VERSION "Linux 4.4.153"
#define CONFIG_SDK_SPI_DEV_NONE 1
#define CONFIG_SDK_BSP_MTD_SPI_NAND_G3 1
#define CONFIG_SDK_RTL826XB 1
#define CONFIG_SDK_BSP_MTD 1
#define CONFIG_SDK_APP_DIAG 1
#define CONFIG_SDK_RTL8218B 1
#define CONFIG_SDK_APP_COMPILE 1
#define CONFIG_SDK_KERNEL_LINUX 1
#define CONFIG_SDK_BSP_USBHCD 1
#define CONFIG_SDK_RTL825XI 1
#define CONFIG_SDK_DRIVER_L2NTFY 1
#define CONFIG_SDK_APP_DIAG_DIR_DIAG_V2 1
#define CONFIG_SDK_TC_TC1_TIME 1
#define CONFIG_SDK_RTL8218D 1
#define CONFIG_SDK_DUMP_TABLE_WITH_NAME 1
#define CONFIG_SDK_RTL825X 1
#define CONFIG_SDK_DEBUG 1
#define CONFIG_SDK_DRIVER_RTCORE 1
#define CONFIG_SDK_RTL8214QF 1
#define CONFIG_TARGET_ARCH_MIPS 1
#define CONFIG_SDK_KERNEL_LINUX_MODULE_LOADABLE 1
#define CONFIG_SDK_DRIVER_NIC 1
#define CONFIG_SDK_KERNEL_LINUX_USER_MODE 1
#define CONFIG_SDK_DRIVER_RTK 1
#define CONFIG_SDK_RTL8214C 1
#define CONFIG_DUAL_IMAGE 1
#define CONFIG_SDK_DRIVER_L2NTFY_R9300 1
#define CONFIG_SDK_RTL826XI 1
#define CONFIG_SDK_RTL9300 1
#define CONFIG_SDK_DEBUG_LOG_LEVEL 3
#define CONFIG_SDK_DRIVER_RTCORE_IN_LINUX_KERNEL 1
#define CONFIG_SDK_DRIVER_NIC_R9300 1
#define CONFIG_FLASH_LAYOUT_TYPE5 1
#define CONFIG_SDK_DRIVER_SPI 1
#define CONFIG_SDK_DEBUG_LOG_MOD_MASK 0xFFFFFFFFFFFFFFFF
#define CONFIG_SDK_RTL8295R 1
#define CONFIG_SDK_LINKMON_MIXED_MODE 1
#define CONFIG_SDK_COMPILER_VERSION "GCC 4.8.5"
#define CONFIG_SDK_RTL825XL 1
#define CONFIG_SDK_BSP_FLASH 1
#define CONFIG_SDK_BSP_MTD_NORSF_G3 1
#define CONFIG_SDK_BSP_SPI_NOR_BOOT 1
