include src/platform/9300/info.in
src/platform/9300/info.in release/Makefile.conf: ;
release/conf.tmp.h:
	@echo "#define OTTO_KSEG2_BASE $(OTTO_KSEG2_BASE)" >> release/conf.tmp.h
	@echo "#define CACHELINE_SIZE $(CACHELINE_SIZE)" >> release/conf.tmp.h
	@echo "#define ICACHE_SIZE $(ICACHE_SIZE)" >> release/conf.tmp.h
	@echo "#define DCACHE_SIZE $(DCACHE_SIZE)" >> release/conf.tmp.h
	@echo "#define OTTO_LX_DEF_FREQ $(OTTO_LX_DEF_FREQ)" >> release/conf.tmp.h
	@echo "#define OTTO_SRAM_DEF_FREQ $(OTTO_SRAM_DEF_FREQ)" >> release/conf.tmp.h
	@echo "#define OTTO_SPI_NOR_START $(OTTO_SPI_NOR_START)" >> release/conf.tmp.h
	@echo "#define OTTO_SRAM_START $(OTTO_SRAM_START)" >> release/conf.tmp.h
	@echo "#define OTTO_SRAM_SIZE $(OTTO_SRAM_SIZE)" >> release/conf.tmp.h
	@echo "#define OTTO_SRAM_MASK $(OTTO_SRAM_MASK)" >> release/conf.tmp.h
	@echo "#define OTTO_SRAM_SIZE_CFG $(OTTO_SRAM_SIZE_CFG)" >> release/conf.tmp.h
	@echo "#define TLB_PAGE_SHIFT $(TLB_PAGE_SHIFT)" >> release/conf.tmp.h
	@echo "#define TLB_PAGE_SIZE $(TLB_PAGE_SIZE)" >> release/conf.tmp.h
	@echo "#define TLB_PAGE_MASK $(TLB_PAGE_MASK)" >> release/conf.tmp.h
	@echo "#define TLB_NUM_TLB_ENTRY $(TLB_NUM_TLB_ENTRY)" >> release/conf.tmp.h
	@echo "#define TLB_NUM_TLB_MASK $(TLB_NUM_TLB_MASK)" >> release/conf.tmp.h
	@echo "#define TLB_ENTRYHI_MASK $(TLB_ENTRYHI_MASK)" >> release/conf.tmp.h
	@echo "#define OTTO_LPLR_ENTRY $(OTTO_LPLR_ENTRY)" >> release/conf.tmp.h
	@echo "#define OTTO_LPLR_SIZE $(OTTO_LPLR_SIZE)" >> release/conf.tmp.h
	@echo "#define OTTO_LPLR_CHECKSUM_OFFSET $(OTTO_LPLR_CHECKSUM_OFFSET)" >> release/conf.tmp.h
	@echo "#define OTTO_SPI_NAND_PLR_ENTRY $(OTTO_SPI_NAND_PLR_ENTRY)" >> release/conf.tmp.h
	@echo "#define OTTO_SPI_NOR_PLR_ENTRY $(OTTO_SPI_NOR_PLR_ENTRY)" >> release/conf.tmp.h
	@echo "#define OTTO_HEADER_OFFSET $(OTTO_HEADER_OFFSET)" >> release/conf.tmp.h
	@echo "#define UART_BASE_ADDR $(UART_BASE_ADDR)" >> release/conf.tmp.h
	@echo "#define MAX_PAGE_BUF_SIZE $(MAX_PAGE_BUF_SIZE)" >> release/conf.tmp.h
	@echo "#define MAX_OOB_BUF_SIZE $(MAX_OOB_BUF_SIZE)" >> release/conf.tmp.h
	@echo "#define MAX_ECC_BUF_SIZE $(MAX_ECC_BUF_SIZE)" >> release/conf.tmp.h
	@echo "#define MAX_BYTE_PER_DMA $(MAX_BYTE_PER_DMA)" >> release/conf.tmp.h
	@echo "#define MAX_ENC_FL_PAGE_NUM $(MAX_ENC_FL_PAGE_NUM)" >> release/conf.tmp.h
	@echo "#define MAX_ENC_FL_TRY_PAGE_NUM $(MAX_ENC_FL_TRY_PAGE_NUM)" >> release/conf.tmp.h
	@echo "#define CC_PLAT_FLAGS $(CC_PLAT_FLAGS)" >> release/conf.tmp.h
	@echo "#define AS_PLAT_FLAGS $(AS_PLAT_FLAGS)" >> release/conf.tmp.h
	@echo "#define PREFERRED_TK_PREFIX $(PREFERRED_TK_PREFIX)" >> release/conf.tmp.h
