/*
 *
 * Automatically generated file; DO NOT EDIT.
 * U-Boot Configuration
 *
 */
#define CONFIG_SDK_FEATURED_MINISDK 1
#define CONFIG_ENV_OVERWRITE 1
#define CONFIG_TFTP_DOWNLOAD 1
#define CONFIG_SPI_NAND_FLASH_G3 1
#define CONFIG_SDK_RTL8224 1
#define CONFIG_SDK_LIBC_VERSION "uClibc-0.9.33.2 with NPTL"
#define CONFIG_RTK_BOOT 1
#define CONFIG_NOR_SPIF_G3 1
#define CONFIG_BOOTARGS "console=ttyS0,38400 mem=256m mtdparts=spi_flash:896K(boot)ro,128K(env),6M(sys),10M(usrimg1),10M(usrimg2),4M(usrappfs),1M(para)"
#define CONFIG_CMD_RTK 1
#define CONFIG_SDK_HW_PROFILE_PROBE_UBOOT_ENV 1
#define CONFIG_IPADDR "192.168.0.30"
#define CONFIG_CMD_PING 1
#define CONFIG_SDK_RTL8218E 1
#define CONFIG_CMD_SAVEENV 1
#define CONFIG_TURNKEY_SYSINFO 1
#define CONFIG_IN_UBOOT 1
#define CONFIG_IH_MAGIC_NUMBER 0x93000000
#define CONFIG_SDK_OS_VERSION "Linux 4.4.153"
#define CONFIG_CMD_FLASH 1
#define CONFIG_UART0 1
#define CONFIG_SDK_SPI_DEV_NONE 1
#define CONFIG_BOARDMODEL "RTL9302C_4xRTL8224_2XGE"
#define CONFIG_SERVERIP "192.168.0.146"
#define CONFIG_CMDLINE_EDITING 1
#define CONFIG_CMD_SF 1
#define CONFIG_ETHADDR "00:E0:4C:00:00:00"
#define CONFIG_OTTO40_PRJNAME "9300_nor_demo"
#define CONFIG_POSTWORD ""
#define CONFIG_AUTOBOOT_PROMPT ""
#define CONFIG_SDK_RTL8218D 1
#define CONFIG_BOARDVERSION ""
#define CONFIG_UBOOT_SDK_SUPPORT 1
#define CONFIG_SDK_DRIVER_RTCORE 1
#define CONFIG_BOOTDELAY 3
#define CONFIG_CMD_IMI 1
#define CONFIG_BOOTCOMMAND "boota"
#define CONFIG_CMD_LOADB 1
#define CONFIG_CMD_RUN 1
#define CONFIG_TARGET_ARCH_MIPS 1
#define CONFIG_SYS_TEXT_BASE 0x83F00000
#define CONFIG_CMD_MEMORY 1
#define CONFIG_NET_MULTI 1
#define CONFIG_BOOT_SPI_NOR 1
#define CONFIG_SPI_NOR_FLASH 1
#define CONFIG_SDK_DRIVER_NIC 1
#define CONFIG_BAUDRATE 38400
#define CONFIG_MISC_INIT_R 1
#define CONFIG_ECC_ENGINE_G2 1
#define CONFIG_DUAL_IMAGE 1
#define CONFIG_SDK_RTL9300 1
#define CONFIG_CMD_LOADS 1
#define CONFIG_SDK_DRIVER_RTCORE_IN_LINUX_KERNEL 1
#define CONFIG_SDK_DRIVER_NIC_R9300 1
#define CONFIG_FLASH_LAYOUT_TYPE5 1
#define CONFIG_CMD_NET 1
#define CONFIG_CFG_PROMPT "RTL9300 # "
#define CONFIG_SDK_DRIVER_SPI 1
#define CONFIG_LZMA 1
#define CONFIG_SDK_COMPILER_VERSION "GCC 4.8.5"
#define CONFIG_SDK_BSP_FLASH 1
#define CONFIG_SDK_BSP_SPI_NOR_BOOT 1
